cmake_minimum_required(VERSION 3.10)

project(gitgame)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED True)

#  1. GTEST

include(FetchContent)
FetchContent_Declare(
    googletest
    URL https://github.com/google/googletest/archive/refs/tags/v1.14.0.zip
    DOWNLOAD_EXTRACT_TIMESTAMP TRUE
)

set(gtest_force_shared_crt ON CACHE BOOL "" FORCE)

FetchContent_MakeAvailable(googletest)

# 2. SOURCE CODE
add_library(GameLib
    src/board.cc
    src/dice.cc
    src/fieldCel.cc
    src/fieldJama.cc
    src/fieldSafe.cc
    src/game.cc
    src/losowanie.cc
    src/player.cc
    src/randomPole.cc
)

target_include_directories(GameLib PUBLIC src)

add_executable(app src/main.cc)
target_link_libraries(app GameLib)


# 3. TEST CODE
enable_testing()

add_executable(run_tests tests/game_tests.cc)
target_link_libraries(run_tests GameLib gtest_main gmock_main)

include(GoogleTest)
gtest_discover_tests(run_tests)
